# Basics of NumPy

Numerical Python is an open source Python library working with numerical data in Python.

In [1]:
pip install numpy     #for installing NumPy

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#for'


In [2]:
import numpy as np    #To access NumPy and its functions

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])      #initialize NumPy arrays


In [4]:
a         #print the given array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
a[0]     #access the first element

array([1, 2, 3, 4])

In [6]:
b = np.array([2, 1, 5, 3, 7, 4, 6, 8])


In [8]:
np.sort(b)      #sorting the array in ascending order

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
p = np.array([1, 2, 3, 4])
q = np.array([5, 6, 7, 8])

In [10]:
np.concatenate((p, q))      #combining both the arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
p.ndim           #no of dimensions of array

1

In [12]:
p.size          #total no of elements in the array

4

In [13]:
p.shape         #shape of the given array

(4,)

In [14]:
p[1]          #indexing

2

In [15]:
p[0:2]        #slicing

array([1, 2])

In [16]:
p[2:]

array([3, 4])

In [17]:
p[-2:]

array([3, 4])

In [19]:
p.min()        #minimum element

1

In [20]:
p.max()       #maximum element

4

In [21]:
p.sum()      #sum of all elements in the given array

10

In [22]:
p.mean()     #to get the average

2.5

In [23]:
p.prod()     #to get the result of multiplying the elements together

24

In [24]:
p.std()     #standard deviation

1.118033988749895

In [25]:
Transpose=p.T   #transpose of the given array

In [26]:
Transpose

array([1, 2, 3, 4])

In [27]:
len(p)         #length of the given array

4

In [29]:
np.sort(p)     #sorting

array([1, 2, 3, 4])

In [30]:
type(p)

numpy.ndarray

In [31]:
p.dtype       #data-type

dtype('int32')